[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
common.path = "../common"

bevy = { workspace = true, features = ["wayland"] }
log.workspace = true

nevy.workspace = true
rustls.workspace = true

avian3d.workspace = true
