[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["wayland"] }
log.workspace = true
nevy.workspace = true
common.path = "../common"
rustls.workspace = true
