[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
common.path = "../common"

bevy.workspace = true
log.workspace = true

nevy.workspace = true
rustls.workspace = true
rcgen = "0.13.1"

avian3d.workspace = true

bevy_landmass = "0.9"
