[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
log.workspace = true
nevy.workspace = true
common.path = "../common"
rustls.workspace = true
rcgen = "0.13.1"
